FROM oven/bun:1
WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/server apps/server
COPY apps/web/package.json apps/web/package.json
COPY packages packages

RUN bun install && bun add drizzle-kit

EXPOSE 3000
CMD ["sh", "-c", "cd packages/db && bunx drizzle-kit push && cd /app && bun run apps/server/src/index.ts"]
